import Head from "next/head";
import Header from "../components/Header";

interface HomeProps {
  posts: any[];
}

export default function Home({ posts }: HomeProps) {
  // handle Search

  return (
    <>
      <Head>
        <title>Reddit-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </>
  );
}
